### ISSUE TITLE
textview can't input when application enter foreground

### ISSUE THREAD

**Issue by hengchengfei** [kenshin03/KTSecretTextView#4]
step1:  inputing text.

step2: application enter background.

step3: application enter foreground.

this time, textview can't input anything.

**Comment by kenshin03** [comment]
Thanks but I wasn't able to reproduce this?

![secret_text_view](https://cloud.githubusercontent.com/assets/831968/6055694/4a4a793c-acb9-11e4-83e2-344bc3d3ed65.gif)

**Comment by kenshin03** [comment]
Closing issue for now. Please re-open if you found a way to reproduce it. Thanks!
